### ISSUE TITLE
Copying equipment is a bit annoying

### ISSUE THREAD

**Issue by redpepper74** [TerryCavanagh/diceymodgeons#37] opened 2020-07-02 02:34 UTC
When creating upgraded, downgraded and weakened versions of equipment, the only detail that's copied over is the name of the equipment. You have to copy the category, color, slots, description, and all the scripts from the original. This is very easy when in the csv or a spreadsheet because all you need to do is copy the line and paste it below, inserting a suffix after its name.

Creating new versions of equipment should cause most or all of the unupgraded equipment's properties to be copied to the new equipment.  A button to duplicate equipment and all its upgrade variants would be useful too. Both of these additions would let modders stay in the editor and not have to edit the csv as often (which should be one of Modgeons' goals, right?).

**Comment by mrcdk** [comment] 2020-07-07 07:14
duplicate of #16 

It'll be available next version!

**Closed by mrcdk** 2020-07-07 07:14 UTC
