### ISSUE TITLE
Unable to change Author name with Edit Information menu

### ISSUE THREAD

**Issue by KusaneHexaku** [TerryCavanagh/diceymodgeons#29] opened 2020-02-04 14:00 UTC
I typoed my name while creating a new mod, so I tried to change it, but it's not allowing me to save my changes.

**Comment by mrcdk** [comment] 2020-02-04 14:07
Thanks for the report! It's already fixed and will be available in the next release 😄 

Duplicate of #26

**Closed by mrcdk** 2020-02-04 14:07 UTC
